#@ load("@ytt:data", "data")

#@ def labels():
app: #@ data.values.name
org: #@ data.values.org
#@ end

apiVersion: apps/v1
kind: Deployment
metadata:
  labels: #@ labels()
  name: #@ data.values.name
spec:
  replicas: 1
  selector:
    matchLabels: #@ labels()
  template:
    metadata: #@ labels()
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:1
          name: #@ data.values.name

#@ if/end data.values.service.enabled:
---
apiVersion: v1
kind: Service
metadata:
  labels: #@ labels()
  name: #@ data.values.name
spec:
  ports:
    - port: #@ data.values.port
      protocol: TCP
      targetPort: #@ data.values.targetPort
  selector: #@ labels()
  sessionAffinity: None
  type: ClusterIP
