apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.18.0
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/projectcontour/contour
          ref: v1.24.2
        includePaths:
          - examples/contour/**/*
