#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

#@ if data.values.website.ingress.domain:
#@ if data.values.website.ingress.secret.certificate and data.values.website.ingress.secret.privateKey:
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ "{}-tls".format(data.values.website.ingress.domain)
type: kubernetes.io/tls
data:
  tls.crt: #@ base64.encode(data.values.website.ingress.secret.certificate)
  tls.key: #@ base64.encode(data.values.website.ingress.secret.privateKey)
#@ end
#@ end
