---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
data:
  key1: value1
  key2: value2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap2
data:
  key1: value1
  key2: value2
