apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: lab-ytt-wrappers-02
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
  workshops:
  - name: lab-ytt-wrappers-02
    capacity: 1
    expires: 15m
    orphaned: 5m
