apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: lab-intro-to-carvel-tools
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
  workshops:
  - name: lab-intro-to-carvel-tools
    capacity: 1
    expires: 30m
    orphaned: 5m
