#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

#@ def docker_config():
#@   server = data.values.options["docker-server"] or "https://index.docker.io/v1/"
#@   credentials = {
#@     "username": data.values.options["docker-username"],
#@     "password": data.values.options["docker-password"],
#@     "auth": base64.encode("{}:{}".format(data.values.options["docker-username"], data.values.options["docker-password"]))
#@   }
#@   if data.values.options["docker-email"]:
#@     credentials["email"] = data.values.options["docker-email"]
#@   end
#@   result = {
#@     "auths": {
#@       server: credentials
#@     }
#@   }
#@   return json.encode(result)
#@ end

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.resource.name
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ base64.encode(docker_config())
